language: python
python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
env:
  global:
    - PROJECT_DIR=$PWD
  matrix:
    - SETUP_COMMAND="install"
    - SETUP_COMMAND="build"
    - SETUP_COMMAND="-q bdist_egg --dist-dir /tmp/easy_install/virtual-node"
install:
  - pip install -r requirements.txt
  - python setup.py $SETUP_COMMAND
script:
  - nosetests
